kind: ClusterServiceVersion
metadata:
  annotations:
    # olm.properties: '[{"type": "olm.maxOpenShiftVersion", "value": "4.14"}]' # Uncomment to specify max OpenShift supported version. 
    #                                                                          # Beware that k8s version is already enforced and this check may prevent
    #                                                                          #  operator installation on newer OpenShift version without a real need.
    features.operators.openshift.io/disconnected: "false"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "true"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"

