configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  backupconfig:
    create: true
    # Avoid backups before waiting for pods (since backup pods could biase the wait)
    baseBackups:
      cronSchedule: '0 5 31 2 *'
    storage:
      azureBlob:
        bucket: backup-with-aks-storage
        path: /backups
        azureCredentials:
          secretKeySelectors:
            storageAccount:
              name: storage-account
              key: account
            accessKey:
              name: storage-account
              key: accessKey
cluster:
  pods:
    persistentVolume:
      size: 128Mi
