configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  backupconfig:
    create: false
cluster:
  pods:
    persistentVolume:
      size: 128Mi
    managementPolicy: Parallel
  managedSql:
    scripts:
      - script: 'CREATE EXTENSION pg_repack'
  postgres:
    extensions:
      - name: pg_repack
nonProductionOptions:
  disableClusterPodAntiAffinity: true
