{{ if and .Values.credentials }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-users
stringData:
{{- with .Values.credentials.patroni }}
  {{- with .restApiPassword }}
  restapi-password: {{ . }}
  {{- end }}
{{- end }}
{{- with .Values.credentials.users }}
  {{- with (.superuser).username }}
  superuser-username: {{ . }}
  {{- end }}
  {{- with (.superuser).password }}
  superuser-password: {{ . }}
  {{- end }}
  {{- with (.replication).username }}
  replication-username: {{ . }}
  {{- end }}
  {{- with (.replication).password }}
  replication-password: {{ . }}
  {{- end }}
  {{- with (.authenticator).username }}
  authenticator-username: {{ . }}
  {{- end }}
  {{- with (.authenticator).password }}
  authenticator-password: {{ . }}
  {{- end }}
{{- end }}
{{ end }}
