configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  backupconfig:
    create: true
    # Avoid backups before waiting for pods (since backup pods could biase the wait)
    baseBackups:
      cronSchedule: '0 5 31 2 *'
    storage:
      gcs:
        bucket: stackgres-e2e-backup-with-gcs-storage-wi
        gcpCredentials:
          fetchCredentialsFromMetadataService: true
cluster:
  pods:
    persistentVolume:
      size: 128Mi
