configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  backupconfig:
    create: true
    # Avoid backups before waiting for pods (since backup pods could biase the wait)
    baseBackups:
      cronSchedule: '0 5 31 2 *'
    storage:
      s3:
        bucket: stackgres-e2e
        awsCredentials:
          secretKeySelectors:
            accessKeyId:
              name: s3-credentials
              key: accessKeyId
            secretAccessKey:
              name: s3-credentials
              key: secretAccessKey
cluster:
  pods:
    persistentVolume:
      size: 128Mi
