- kind: SGCluster
  name: sgclusters.stackgres.io
  version: v1
  displayName: StackGres Cluster
  description: Main CRD, manages Postgres clusters (one or more Postgres pods)
- kind: SGInstanceProfile
  name: sginstanceprofiles.stackgres.io
  version: v1
  displayName: StackGres Instance Profile
  description: Instance Profiles are like "t-shirt" sizes, used for pods sizing
- kind: SGPostgresConfig
  name: sgpgconfigs.stackgres.io
  version: v1
  displayName: StackGres Postgres Configuration
  description: Strongly validated customized Postgres configuration (postgresql.conf)
- kind: SGPoolingConfig
  name: sgpoolconfigs.stackgres.io
  version: v1
  displayName: StackGres Connection Pooling Configuration
  description: Customized PgBouncer (connection pooler) configuration
- kind: SGObjectStorage
  name: sgobjectstorages.stackgres.io
  version: v1beta1
  displayName: StackGres Object Storage
  description: Handle to an existing Object Storage (e.g. S3), used to store backups
- kind: SGBackup
  name: sgbackups.stackgres.io
  version: v1
  displayName: StackGres Backup
  description: Handle to a performed (or to be performed, if run manually) backup
- kind: SGDbOps
  name: sgdbops.stackgres.io
  version: v1
  displayName: StackGres Database Operation
  description: Day 2 Operations, including upgrades, restarts, vacuum, repack, etc
- kind: SGScript
  name: sgscripts.stackgres.io
  version: v1
  displayName: StackGres Script
  description: Managed SQL Scripts, used for initial SQL commands or migrations
- kind: SGDistributedLogs
  name: sgdistributedlogs.stackgres.io
  version: v1
  displayName: StackGres Distributed Logs
  description: Multi-tenant logs server, to aggregate Postgres logs. Fully managed
- kind: SGShardedCluster
  name: sgshardedclusters.stackgres.io
  version: v1alpha1
  displayName: StackGres Sharded Cluster
  description: Manages Postgres sharded clusters (two or more SGClusters)
- kind: SGShardedBackup
  name: sgshardedbackups.stackgres.io
  version: v1
  displayName: StackGres Sharded Backup
  description: Handle to a performed (or to be performed, if run manually) backup for sharded clusters
- kind: SGShardedDbOps
  name: sgshardeddbops.stackgres.io
  version: v1
  displayName: StackGres Sharded DbOps
  description: Day 2 Operations for sharded clusters, including restarts, resharding, etc
- kind: SGStream
  name: sgstreams.stackgres.io
  version: v1alpha1
  displayName: StackGres Stream
  description: Stream Change Data Captured (CDC) events
- kind: SGConfig
  name: sgconfigs.stackgres.io
  version: v1
  displayName: StackGres Operator Configuration
  description: Operator configuration for OLM-based installations (equivalent to values.yaml with Helm)
