configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  backupconfig:
    create: false
cluster:
  pods:
    persistentVolume:
      size: 128Mi
    managementPolicy: Parallel
  configurations:
    observability:
      prometheusAutobind: true
nonProductionOptions:
  disableClusterPodAntiAffinity: true
