# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
$(
  yq -y 'del(.spec.versions[1])' config/crd/bases/SGBackup.yaml > config/crd/bases/SGBackup.yaml.tmp
  mv config/crd/bases/SGBackup.yaml.tmp config/crd/bases/SGBackup.yaml
  if [ "$CREATE_CONVERSION_WEBHOOKS" = true ]
  then
    for CRD in $(cat config/crd/bases/index.txt)
    do
      yq -y '.spec.conversion = {
        strategy: "Webhook",
        webhook: {
          clientConfig: {
            caBundle: "Cg==",
            service: {
              namespace: "system",
              name: "stackgres-operator",
              path: ("/stackgres/conversion/" + .spec.names.singular)
            }
          },
          conversionReviewVersions: [ "v1" ]
        }
      }' "config/crd/bases/$CRD" > "config/crd/bases/$CRD.tmp"
      mv "config/crd/bases/$CRD.tmp" "config/crd/bases/$CRD"
    done
  fi
  sed 's#^#- bases/#' config/crd/bases/index.txt | grep -v '^$'
)
#+kubebuilder:scaffold:crdkustomizeresource
