configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  backupconfig:
    create: false
cluster:
  pods:
    persistentVolume:
      size: 128Mi
nonProductionOptions:
  disableClusterPodAntiAffinity: false
