configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '24MB'
  objectstorage:
    create: true
cluster:
  pods:
    persistentVolume:
      size: 128Mi
  configurations:
    backups:
      cronSchedule: '0 5 31 2 *'
      sgObjectStorage: backupconf
nonProductionOptions:
  disableClusterPodAntiAffinity: true
