configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  objectstorage:
    create: true
cluster:
  pods:
    persistentVolume:
      size: 128Mi
  configurations:
    backups:
      retention: 2
      cronSchedule: '0 5 31 2 *'
      sgObjectStorage: objectstorage
nonProductionOptions:
  disableClusterPodAntiAffinity: true
