configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  backupconfig:
    create: false
cluster:
  pods:
    persistentVolume:
      size: 128Mi
    managementPolicy: Parallel
  initialData:
    restore:
      downloadDiskConcurrency: 1
nonProductionOptions:
  disableClusterPodAntiAffinity: true
