name: 'Repo Lockdown'

on:
  issues:
    types: opened
  pull_request_target:
    types: opened

permissions:
  issues: write
  pull-requests: write

jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v3
        with:
          github-token: ${{ github.token }}
          issue-comment: >
            This repository is just a mirror and does not accept bug reports,
            the primary repository is located at https://gitlab.com/ongresinc/stackgres
          skip-closed-issue-comment: true
          pr-comment: >
            This repository is just a mirror and does not accept pull requests,
            the primary repository is located at https://gitlab.com/ongresinc/stackgres
          skip-closed-pr-comment: true
